### ISSUE TITLE
🐛 [SABnzbd+Plex NAS] Ingress Support

### ISSUE THREAD

**Issue by dm82m** [alexbelgium/hassio-addons#1022]
### Description

Hey @alexbelgium,

would be great to support ingress for SABnzbd and Plex NAS.

Any idea if you would do that in the future?

Best,
Dirk 

### Reproduction steps

```bash
Not needed, Feature request.
```

### Addon Logs

```bash
Not needed, Feature request.
```

### Architecture

amd64

### OS

HAos

**Comment by dm82m** [comment]
@alexbelgium ?

**Comment by alexbelgium** [comment]
Hi, it is very unlikely, as apps such as plex are very complex and have securities in place that prevent using ingress. I think I had tested some time ago. Alas I really don't have much time to add new features for the moment so I won't really be able to look at that in a near future.

The best for you would likely to open the port externally and connect using a free domain name such as duckdns or the nabu casa one

Ps: the stale tag appears because you have opened it as an issue and not a request (which is not impacted by the autostale).
