### ISSUE TITLE
🐛 [readarr] Update info page with better information

### ISSUE THREAD

**Issue by airtonix** [alexbelgium/hassio-addons#1088]
### Description

> Configurations can be done through the app webUI, except for the following options

![image](https://github.com/alexbelgium/hassio-addons/assets/61225/5c7d45e2-b5bb-4208-bb28-18d3e768478c)

so how do we (as homeassistant users) do that configuration? 

perhaps this info page for the addon should then go on to say something like: 

- Using an editor on the homeassisntant server (like Studio Code Server), edit the `/config/addons_config/readarr/config.xml` ? 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
not relevant
```

### Architecture

amd64

### OS

HAos

**Comment by ciB89** [comment]
> so how do we (as homeassistant users) do that configuration?

Through the add-on configuration on the add-ons page:

![image](https://github.com/alexbelgium/hassio-addons/assets/20285334/27340d6e-30dd-4010-8f4b-03b66cfffc34)
![image](https://github.com/alexbelgium/hassio-addons/assets/20285334/6b192fa0-8e0d-498b-b9ae-f7b92ce482eb)

**Comment by ciB89** [comment]
You can find and modify the config.xml file of readarr in `\config\addons_config\readarr`

**Comment by alexbelgium** [comment]
Hi, thanks ciBB9

Indeed, some options can be configured in the addon options ; otherwise most of the configuration can be done with the webui http://homeassistant:8787 ; and as ciBB9 mentioned for advanced modifications on the config.xml it is done through the data folder in the location he mentioned

A note : /config/addons_config/readarr/config.yaml is not linked to readarr itself, but it is a way to inject custom ENV variables : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-add-env-variables

By the way, is ingress working for you? I reinstalled the addon to test on my system and Ingress is blank

**Comment by alexbelgium** [comment]
I see, there is a bug : the config.xml taken into account is located in /config/addons_config/readar/config.yaml/config.xml instead of /config/addons_config/readar/config.xml . Easy enough fix I'll push a new version

**Comment by alexbelgium** [comment]
Pushed again a new version : I had modified the authentification as "external" to align with radarr & sonarr addons, but it seems that this is not implemented yet for readarr

**Comment by airtonix** [comment]
> You can find and modify the config.xml file of readarr in `\config\addons_config\readarr`

if you read my issue ticket, you'll see that I already know this.


> Indeed, some options can be configured in the addon options ; otherwise most of the configuration can be done with the webui http://homeassistant:8787 ; and as ciBB9 mentioned for advanced modifications on the config.xml it is done through the data folder in the location he mentioned

I should be clearer, this ticket is really a request to update the info page with better, more clear information.

For first time users, it's not obvious that: 

1. you have to go and edit a file
2. that the file is `/config/addons_config/readar/config.yaml/config.xml`
3. that in order to get to `/config/addons_config/` you need to either:
  1. ssh somehow to the server
  2. install an addon like Studio Code Server 

We can't really help those who dont know what ssh or what a file is. And you can't really assume that the setup wasn't inherited.

So to assist the 90% cases: 

> perhaps this info page for the addon should then go on to say something like:

> > Using an editor on the homeassisntant server (like Studio Code Server),
> > edit the /config/addons_config/readarr/config.xml ?


> By the way, is ingress working for you? I reinstalled the addon to test on my system and Ingress is blank

My other ticket #1089 says no.

**Comment by alexbelgium** [comment]
Hi, actually the easiest way to access the files is with my file browser addon. Watch out that due to how HA now works (voluntary behavior from the devs), addon configs are either in /addon_configs/nameoftheaddon ; or non /homeassistant/addons_config/nameoftheaddon depending on whether my add-ons have implemented the new HA logic or not. It's a lot confusing, I know, but that's how HA itself is set...

Thanks for the readme update, indeed I understand how this is confusing for newcomers. Actually now ingress should work (at least on my system with a new install) so I'll check the other ticket what could be the cause.

Thanks!
