### ISSUE TITLE
Scrutiny: ingress support

### ISSUE THREAD

**Issue by ElVit** [alexbelgium/hassio-addons#11]
Hi @alexbelgium,
is it possible to add **[ingress ](https://developers.home-assistant.io/docs/add-ons/presentation/#ingress)support**?
I don't know how difficult it is but it would be nice to access scrutiny from my (sub) domain.
Since scrutiny is not password protected I don't want to add it via `panel_iframe`.

**Comment by alexbelgium** [comment]
That's a good question. I will try but not sure what are the exact requirements.

Btw, I've put a temporary fix for the blank screen on mobiles - it should now work (with a bad layout, but at least a visible one) :-)
And I've removed the "full access" flag as it doesn't seem required anymore.

**Comment by ElVit** [comment]
Wow thank you it’s working now :)
Now I can see the scrutiny web page in iOS Safari.

**Comment by alexbelgium** [comment]
I've spent some time trying to implement nginx. It was quite complex as the system was really not developed for that (for example, they use relative urls to the base domain everywhere...). It's nearly working - the nginx server is set, the urls were converted from relative to base to relative to the subfolder, there is only one big issue.

Some relative-to-domain url are hardcoded in the app (actually it is : /api/summary instead of api/summary)... So I need the developer to merge this PR before nginx can work with subfolders : https://github.com/AnalogJ/scrutiny/pull/93

Well it was an interesting development I learned a lot so thanks! And I'll continue once this can be fixed

**Comment by alexbelgium** [comment]
@ElVit Update : ingress implemented ! Please try the latest version named "27b923b5-ls11-ingress" :-)
With ssl support.

**Comment by ElVit** [comment]
Hi @alexbelgium ,
Thank you for implementing this nice feature this fast. It’s working for me too. And also the bug with the blank screen is gone now. Very good job 👍🏼

**Comment by ElVit** [comment]
Here is an other suggestion for a small optical improvement: Could you please add an panel icon to the sidebar?

In config.json:
`"panel_icon": "mdi:glasses",`

**Comment by alexbelgium** [comment]
@ElVit  Thanks very much! I've implemented it in a new version rev3
