### ISSUE TITLE
🐛 [Immich] version pgvecto.rs missmatch

### ISSUE THREAD

**Issue by Doomic** [alexbelgium/hassio-addons#1232]
### Description

I get the following error:
The pgvecto.rs extension version is 0.1.13 instead of 0.1.11.
I have updated both Immich (1.94.1) and postgres(15.5-6) to latest version. Changelog is telling I needed to upgrade both, but it looks like pgvecto.rs in the postgres container has been downgraded afterwards, maybe that is the issue; but not sure.
Hope you can fix it.
And thanks for writing the add-ons

### Reproduction steps

```bash
Starting the Immich addon gives the following error in the log
The pgvecto.rs extension version is 0.1.13 instead of 0.1.11.
```

### Addon Logs

```bash
Error: 
        The pgvecto.rs extension version is 0.1.13 instead of 0.1.11.
        Please run 'DROP EXTENSION IF EXISTS vectors' and switch to 0.1.11, such as with the docker image 'tensorchord/pgvecto-rs:pg15-v0.1.11'.
    at DatabaseService.assertVectors (/app/immich/server/dist/domain/database/database.service.js:47:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseService.init (/app/immich/server/dist/domain/database/database.service.js:32:9)
    at async AppService.init (/app/immich/server/dist/immich/app.service.js:56:9)
    at async AppModule.onModuleInit (/app/immich/server/dist/immich/app.module.js:32:9)
    at async callModuleInitHook (/app/immich/server/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/app/immich/server/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/app/immich/server/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/app/immich/server/node_modules/@nestjs/core/nest-application.js:169:33)
    at async bootstrap (/app/immich/server/dist/immich/main.js:34:20)

Node.js v20.11.0
```

**Comment by alexh3o** [comment]
Hi, I have the same behaviour, on:
Home Assistant OS 11.4
Core 2024.1.6
Supervisor 2023.12.1
Raspberry Pi 4

I upgraded both postgres and immich, but I get the message "The pgvecto.rs extension version is 0.1.13 instead of 0.1.11."
I uninstalled, deleted all postgres files that were still in /data, reinstalled both with no success.

Everything was working before the update.

**Comment by alexbelgium** [comment]
> Hi, I have the same behaviour, on: Home Assistant OS 11.4 Core 2024.1.6 Supervisor 2023.12.1 Raspberry Pi 4
> 
> Edit: it's working, starting correctly now. The only thing i can see that I did, even if probably not related, is changing the "networkdisks" root of the SMB share where i store data and the path of data_location...

Hi, sorry do you mean that everything is starting as it should? so there is no more the error "The pgvecto.rs extension version is 0.1.13 instead of 0.1.11." ?

**Comment by alexbelgium** [comment]
> ### Description
> I get the following error: The pgvecto.rs extension version is 0.1.13 instead of 0.1.11. I have updated both Immich (1.94.1) and postgres(15.5-6) to latest version. Changelog is telling I needed to upgrade both, but it looks like pgvecto.rs in the postgres container has been downgraded afterwards, maybe that is the issue; but not sure. Hope you can fix it. And thanks for writing the add-ons

Thanks ; actually I can't repeat this issue. Do you have portainer installed? If yes, could you please go in the postgres addon and copy paste the command :
```
echo "\dx
\q"> setup_postgres.sql
psql "postgres://postgres:homeassistant@localhost:5432" < setup_postgres.sql | grep vectors
```

Please change "homeassistant" if you have defined a different password for your database ; thanks!

**Comment by alexh3o** [comment]
> Hi, sorry do you mean that everything is starting as it should? so there is no more the error "The pgvecto.rs extension version is 0.1.13 instead of 0.1.11." ?

Yes it is starting properly, no errors

> like @alexh3o I also use a SMB share for the storage location; not sure what he edited; however i can not relate it to the error in the log...

I did tried a lot of things (ha su repair, host reboots, deleted residual postress files after uninstall...) which did not seem to do anything, I still had the same error than you and no server start.
Then I changed the paths in the addon UI config. Mounted the SMB share at its root instead of within the photos folder. It seems unrelated indeed so I don't know why it's working now and why it wasn't for the 24 hours after both addons update.
Everything had to be recreated from a different data path and it is currently still reindexing my collection from scratch. I also added a photos_location parameter but it's probably ignored and unrelated anyway.

Changed from
```
data_location: /mnt/0-Photos/
cifsdomain: WORKGROUP
networkdisks: //192.168.1xxx/SMBShare/0-Photos
```
to 
```
data_location: /mnt/SMBShare/AppData/immich
photos_location: /mnt/SMBShare/0-Photos
cifsdomain: WORKGROUP
networkdisks: //192.168.1xxx/SMBShare/
```

**Comment by alexbelgium** [comment]
Well well well so from the analysis made above you DO have version 0.1.1 installed based on your portainer check `vectors | 0.1.1`  so can't understand the `The pgvecto.rs extension version is 0.1.13 instead of 0.1.11` error...

I think it's another of Immich fragility : it initially encountered the postgres vector extension 0.1.13 and is now blocked, even though the actual vector extension is now 0.1.1...

I would recommend to you if possible : restore postgres addon from a version prior to updating immich (which should remove the pq_vector table from postgres); then restart immich which should trigger the re-creation of the pg_vector database table. You could also try to backup the postgres addon, then go with Filebrowser in the /addon_configs/xxx-postgres folder and delete it's database, then recreate it by restarting postgres, then immich... If it fails you can always restore your postgres addon

Luckily it should be a once and for all, as Immich should not implement any other major breaking change such as this one in a too near future

**Comment by alexbelgium** [comment]
I confirm : I installed from scratch postgres & immich addons and it worked straight away... So it seems this bug is due to immich having seen at one point the version 0.1.13 of the extension and keeping a memory of it somewhere... So alas it seems that due to "active development mode" of both postgres & immich the best action is either to restore an old backup and re-update to perform the migration with 0.1.1 ; or just delete the database and re-create it...

**Comment by alexh3o** [comment]
> I think it's another of Immich fragility : it initially encountered the postgres vector extension 0.1.13 and is now blocked, even though the actual vector extension is now 0.1.1...

A detail that maybe helps the analysis, I did update and unsuccessfully start immich before updating postgres to the proper version. So latest immich first started with the 0.1.13 pgvector indeed.
Now all works well.

**Comment by alexbelgium** [comment]
Thanks very much ; pretty sure this is the issue. Pgvector created the database but it does not support downgrading ; so every database that saw 0.1.13 are doomed... Or would need a manual modification that could be tricky

**Comment by mihai205** [comment]
What worked for me was to manually delete vector extension with pgAdmin and then restart postgress and Immich.

**Comment by Doomic** [comment]
@alexh3o thanks; i tried change the path; but that is not working; but i understand that you are reindexing; meaning you have a clean install (i guess). I can't find a way to reindex the default library inside immich.. and not sure if my phone gets it; that the files are already uploaded to immich.

@mihai205 ; what do you mean with "manually delete"? is that the "DROP EXTENSION vector" statement? because i have tried that already; and it looks that this statement is executed every time the immich addon is restarted. 

The problem is that i do not have a backup (i only keep a backup for 3 days; and had autoupdate checked.. so i learned my leason)... therefore still trying to recover the database.

what i found was `UPDATE pg_catalog.pg_extension SET extversion = '0.1.x' where extname = 'vectors';`  in the upgrade guide of pgvecto.rs.. if i update this extversion cell to '0.1.11' it is no longer logging about the version missmatch... but (as expected) there are other errors to be fixed; not sure if i should dive in these errors or find another workaround.
however; this confirms that there are leftovers of a 0.1.13 version that was published

**Comment by mihai205** [comment]
![pgAdmin-vectors](https://github.com/alexbelgium/hassio-addons/assets/65603209/6084f730-058f-4edb-b47a-130847b1d6b7)
navigate with pgAdmin to your immich db, toggle the extensions to view the list and with right click on vectors, select delete. I've restarted postgres and after that restarted immich. 

hope this helps

**Comment by Doomic** [comment]
@mihai205 this was the fix; thank you!
I did not expect that this would work; because i guessed that rightclick->delete should do the same as the drop extension query...

What i did (not sure if it is imortant)
I kept both addons running; did the delete as you described; restarted the postgres addon; went to the immich addon (and saw already positive signs in the logs; just to be sure -) i restarted immich as well.. went to my immich url/webui and everything was looking as it was before.
