### ISSUE TITLE
Request - Firefly iii

### ISSUE THREAD

**Issue by gieljnssns** [alexbelgium/hassio-addons#126]
If you have some time, can you make an addon of Firefly iii?
"Firefly III" is a (self-hosted) manager for your personal finances. It can help you keep track of your expenses and income, so you can spend less and save more. Firefly III supports the use of budgets, categories and tags. Using a bunch of external tools, you can import data. It also has many neat financial reports available.
https://www.firefly-iii.org

It can be installed as a docker container.
https://docs.firefly-iii.org/firefly-iii/installation/docker/

**Comment by alexbelgium** [comment]
Hi, I'm off for the moment I'll look at it next week!

**Comment by sbonn13** [comment]
I am also searching for this addon. Due to the fact that the previous community version is deprecated I was not able to find any alternative. I remember there were some issues with the ingress integration of the docker file. I assume this is not really required if we think of a non-integrated installation. We just would like to use the docker environment home assistant is using. Similar to the nextcloud addon. Only due to the missing nabu casa/ ingress functionality it was set to status deprecated I assume.

@alexbelgium If you would like to share your knowledge on how to integrate existing docker files as a new addon into nextcloud and their parameterization we might support in future?

The repository of the deprecated version:
https://github.com/hassio-addons/addon-firefly-iii

By the way; Merry Christmas! Enjoy the festive days and thank you very much for this gerat repository and your contribution!

**Comment by alexbelgium** [comment]
Thanks very much for your message! I'll look at it in the coming days, indeed ingress implementation really depends of how the app itself is built, if it accepts dynamic sundomains... It roughly takes 5x more time for an ingress implementation (if feasible) and also

**Comment by alexbelgium** [comment]
Thanks very much for your message! I'll look at it in the coming days, indeed ingress implementation really depends of how the app itself is built, if it accepts dynamic sundomains... It roughly takes 5x more time for an ingress implementation (if feasible) and also increases the probability of braking changes in the future with my automatic update. So, I'll see but no promises :)

Have great holidays you too, merry Christmas and hoping everything is for the best for you!

**Comment by alexbelgium** [comment]
Hi, I've pushed a first version. It is a little complex as I try to support 4 ways of connecting the database : sqlite (default, embedded in the addon) ; MariaDB (auto-detection if the MariaDB addon is installed and runs), and external databases (mysql and pgsql). If you have some time your feedback will be welcome!

**Comment by alexbelgium** [comment]
v1.1 pushed to correct typos

**Comment by alexbelgium** [comment]
addon starts without errors but no UI yet, investigating

**Comment by alexbelgium** [comment]
ok webUI works :-). The addon seems functional, I've tested only with sqlite for now. Please let me know if you have any feedbacks!

**Comment by alexbelgium** [comment]
remanence still has an issue and it messed up everything. I'll come back to it tomorrow

**Comment by steef84** [comment]
Wow nice package. Will try tomorrow also and test :). Just tried now but webui stays blank. Just uninstalled for now

**Comment by alexbelgium** [comment]
Yup, not working yet... Some technicalities make it more complex than I expected :)

**Comment by alexbelgium** [comment]
Ok, now version 1.6 should work with sqlite (and other database modes that I have not tested) :-)
Simple permissions issues. The addon Readme should describe in a hopefully precise enough way how to set it! 
Normally simply installing and running the addon should work with the basic sqlite database

**Comment by alexbelgium** [comment]
Confirmed working :-)

**Comment by gieljnssns** [comment]
Tanks a lot. I've just installed with mariadb!

Confirmed working

**Comment by steef84** [comment]
Yep also working here as it seems, using sqlite. Nice app, need to discover all its possibilities.  Good job making it avavaible Alex!

**Comment by alexbelgium** [comment]
Thanks for the feedbacks!

**Comment by gieljnssns** [comment]
I'm also discovering all possibilities from firefly.
I was trying to import data from my bank, but there seems to be another docker container for importing data.
https://docs.firefly-iii.org/data-importer/install/docker/

**Comment by alexbelgium** [comment]
Indeed... I'll look at it also. 

BTW, the upload folder is not remanent in the firefly iii addon due to how they configured it, but I don't know the impact. The database itself is remanent (kept upon addon reboot or update).

**Comment by sbonn13** [comment]
Works perfectly with mariadb_addon! Many thanks!
And yes @gieljnssns is right, I have recognized now the same, the import tool is a separate docker image.

**Comment by alexbelgium** [comment]
Hi, the import tool is up, could you please test it? thanks

**Comment by alexbelgium** [comment]
As long as everything works I'll close the request, enjoy all

**Comment by alexbelgium** [comment]
btw, don't hesitate if you use it to improve the Readme file to help other users! I'm not a user myself so there are some things that might be needed to describe that I do not know. Thanks

**Comment by steef84** [comment]
Will certainly do when having some time and things 100% up and running. Still getting things setup properly, cannot even import data for now :)

**Comment by sbonn13** [comment]
Works nice, thank you very much especially as you are not even using the tool on your own!

**Comment by steef84** [comment]
Happy new year all

Been trying for some days to let `Firefly iii Data Importer` connect to `Firefly iii`. Connection fails, I guess, because both containers are not om te same network. URL cannot be resolved. (cURL error 6 seen In webinterface `Firefly iii Data Importer` ) Tried to connect both containers via portainer to join the same network `bridge` but no joy for me. Googleing how to connect containers with each other has something to do with enabling ICC if I read correctly Anyone succeded in connecting the importer to firefly itself or got the golden tip for me? Docker is quit new for me. Running on PI4.

**Comment by alexbelgium** [comment]
Happy new year! I think you need to use the local ip address of your HA instance with the port from firefly. I don't think HA authorises addons to communicate on its internal docker ip network. Usually that's what I do to make addons communicate

**Comment by ElVit** [comment]
Hi @alexbelgium and thanks for this nice addon. 
Since my current multi banking tool changed from free to only paid model I am searching for a new tool. 
Firefly III seems to be a good alternative for me.
In the docs I found that there is an other importer available:
https://github.com/bnw/firefly-iii-fints-importer

I would be very happy if you had time to offer this as an addon as well 😃
