### ISSUE TITLE
🐛 [Scrutiny-FA] Not starting after upgrade to 0.8.1

### ISSUE THREAD

**Issue by dm82m** [alexbelgium/hassio-addons#1344]
### Description

After update to latest version I get a „502: Bad Gateway“. Nothing bad in the logs.

![IMG_6256](https://github.com/alexbelgium/hassio-addons/assets/736311/791d0f04-e1a1-474e-aa50-e23a8c85bf8b)

### Reproduction steps

```bash
Do the update and try to access the UI.
```

### Addon Logs

```bash
Nothing special
```

### Architecture

amd64

### OS

HAos

**Comment by chertvl** [comment]
![image](https://github.com/alexbelgium/hassio-addons/assets/38353584/4b8d8cdb-0538-4c7e-97aa-a4beaba9c855)

There is what I see after update to 0.8.1
Endless logo ;)

**Comment by dm82m** [comment]
the addon itself is running, if I try to access the webui the supervisor logs says:
`2024-04-13 08:11:12.352 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.11:8099 ssl:default [Connect call failed ('172.30.33.11', 8099)]`

**Comment by alexbelgium** [comment]
Hi, thanks - error is "./run not found" which means a path has changed in the upstream container. I'll check that today or Tomorrow at latest

**Comment by alexbelgium** [comment]
Update : likely issue is with shebang `#!/usr/bin/with-contenv bashio` used in ./run

**Comment by alexbelgium** [comment]
À short term solution is to open the container in portainer and run `nginx` otherwise i'll push a fix in around 12h

**Comment by dm82m** [comment]
I reverted to last version. Isn’t there a testing before new releases are pushed to public? We had a broken update already with the last release and now again. That feels ungood to be the beta tester after upgrades of your addons.

**Comment by alexbelgium** [comment]
> I reverted to last version. Isn’t there a testing before new releases are pushed to public? We had a broken update already with the last release and now again. That feels ungood to be the beta tester after upgrades of your addons.

It seems there is a major misunderstanding about what this repo is! I am not paid, and not an official moment from any of HA, scrutiny, or other. Therefore if you expect a premium treatment with perfectly stable softwares and answers in less than 12 hours, you would probably but much happier with commercial softwares. 

Github is a community for developers, which help each other on their own home to freely provide solutions to other people. I certainly hope that you don't depend on this app for your commercial activity !

BTW if you had checked a bit further, the app perfectly works when accessed from the webui. And data continued to be registered. Only the ingress part didn't.

Also btw, the strict minimum that you could do to show support for this addon and it's free support is to star the repo, which you haven't even done.

This said, i'll update the addon when i'll have time during my weekend, have a nice day

**Comment by dm82m** [comment]
Sorry alexandre, I didn’t want to offend you. I was just thinking what we could do in the direction of testing releases before they are rolled out to all users. Maybe beta release first, if a few positive responses are there do the final release to public.

i am absolutely aware of the fact you aren’t payed for your open source contributions! Same applies to me for my stuff.

and I am not using your addon commercially, just private.

can you explain what starring repos is used for? Why is that “support”? Thought it is to remember important once, like marking as favorite or so.

**Comment by dm82m** [comment]
Works with 0.8.1-2 - thanks for your work and have a nice weekend!

**Comment by alexbelgium** [comment]
> Sorry alexandre, I didn’t want to offend you. I was just thinking what we could do in the direction of testing releases before they are rolled out to all users. Maybe beta release first, if a few positive responses are there do the final release to public.
> 
> i am absolutely aware of the fact you aren’t payed for your open source contributions! Same applies to me for my stuff.
> 
> and I am not using your addon commercially, just private.
> 
> can you explain what starring repos is used for? Why is that “support”? Thought it is to remember important once, like marking as favorite or so.

Hi, no offense taken but indeed such repo is a very complex task and I already take way too much time to maintain it ;)

Out of the 80+ addons I perhaps use regularly around 5 ; all the others are only there as requests from users or because people are using them. I've therefore set the addons in a way that tries to be the most self-reliant way, with helper scripts automatically updating addons every week when a new upstream version was pushed ; installing dependencies ; and trying to anticipate upstream changes.

But because of that, indeed I cannot propose anything other than depending on users to escalate breakages. Honesty, such breakages sometimes come from HA itself, or the upstream app, so breakages are not only due to how the addons are designed. Having public tests would be much too time consuming for all those addons... I would therefore have to globally close the repo. However I try to use issue (such as the one you escalated) to build universal solutions : for example I've set an helper script that will now check for all addons if this issue could occur and prevent it.

Regarding starting repos, indeed it can be used as a bookmarking tool. But it is also greatly used to show appreciation to a maintainer and signal to other people on the internet if the repo is useful or not. For example, this affects ranking in search results : https://docs.github.com/en/get-started/exploring-projects-on-github/saving-repositories-with-stars#about-stars . In the end, it doesn't bring me anything really except that people appreciate all those hours I spend on my private or family time to update and support (for example answering on those threads, quickly solving issues) the addons.

That said, i'm happy it works again and wish you a nice weekend. I can only recommend also that you disable automatic update as usually if there are issues reported it would be on the weekend
