### ISSUE TITLE
🐛 Nextcloud: App cannot be installed because it makes the server unstable

### ISSUE THREAD

**Issue by gsmolamodzzz** [alexbelgium/hassio-addons#1386]
### Description

Every time I try as admin to install an app in my nextcloud instance, I get the message that this makes the server unstable. Unfortunately, this has been going on all along and I thought that the problem would be fixed with version 29.0.0.19, but unfortunately this is not the case

### Reproduction steps

```bash
Go to Profile
> Apps > try to install any Apps > error
```

### Addon Logs

```bash
migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /data/config/keys
Initializing nextcloud 29.0.0.19 (this can take a while) ...
Setting permissions
Initializing finished
Starting...
/etc/cont-init.d/02-init_steps.sh: executing
Setting logs
 
 
----------------------------------------
 Nextcloud 29.0.0.19 is installed 
----------------------------------------
... checking for app updates
All apps are up-to-date or no updates could be found
... Clean potential errors
Maintenance mode already disabled
... Remove CODE if installed as not compatible
... Disabling check_data_directory_permissions
System config value check_data_directory_permissions set to boolean false
    0 [>---------------------------]    0 [->--------------------------]    0 [--->------------------------]    0 [----->----------------------]    0 [------->--------------------]post_max_size set to 2056
... enabling thumbnails
System config value preview_ffmpeg_path set to string /usr/bin/ffmpeg
System config value enable_previews set to string true
/etc/cont-init.d/02-mariadb_discovery.sh: executing
---
HAos

**Comment by frb01** [comment]
Hello, given that we cannot install the applications, how can I install the applications manually with occ and in which applications (portainer?). I wanted to install 'Brute-force settings' because I have an error message in Nextcloud "Your network address has been identified as "192.168.1.254" and it is restricted by the anti-intrusion mechanism which slows down the performance of certain requests. If this network address is not yours, this could mean that there is a proxy configuration error?
Thanks

**Comment by alexbelgium** [comment]
Hi, it's a complex issue indeed. Actually the apps are installed, but not enabled  you can use two methods from this thread to enable manually :  https://github.com/alexbelgium/hassio-addons/issues/1333#issuecomment-2046801286 or this one https://github.com/alexbelgium/hassio-addons/issues/1333#issuecomment-2090281733

**Comment by frb01** [comment]
Hello and thank you, finally I succeeded, I went through portainer, you just have to find the exact word of the application for the occ line. I am left with an error in Nextcloud: "Your web server is not configured correctly to resolve `.well-known` URLs, failed on: `/.well-known/caldav`". (I think because I installed it on an external usb3 ssd drive from rapsberry "/mnt/sdb1/nextcloud" and after installation, it is found in /media/ssd1t/nextcloud). For this error, I cannot find a solution.

**Comment by alexbelgium** [comment]
Nextcloud is annoying they don't seem to really care about breaking things... There even is a thread here : https://help.nextcloud.com/t/frequent-nextcloud-29-hub-8-update-issues/189897 Well they say that nginx proxies are our responsibility. The nginx proxy we are is configured by linuxserver's nextcloud image but there is not much activity going there to solve those issues...

**Comment by frb01** [comment]
Thanks, i keep like this ? It's not "grave" ?
