### ISSUE TITLE
❓ [Guacamole] Reenter totp

### ISSUE THREAD

**Issue by dasb00ter** [alexbelgium/hassio-addons#1691]
**Which addon?**

name: 
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

---

**Which addon?**
Guacamole hassio addon

**Addon or app?**

**Describe the solution you'd like**

How can I re-enter into totp with this addon without losing all my client set up? I have found my way to the addon config folder but nothing jumps out at me? Thanks for making it so easy to set up and use with HACs it was my own fault when I reset my phone that I lost the key for totp

**Describe alternatives you've considered**

**Additional context**

**Comment by alexbelgium** [comment]
Hi, I don't use this app so can't really answer. You should probably post in the guacamole upstream repo https://github.com/abesnier/docker-guacamole

**Comment by dasb00ter** [comment]
Thanks. Just to clarify by app you mean the addon? You have made it work with hassio but don't have info about it's actual working? I could see some issue where somebody stated that they deleted the addon but it still requested the old totp code when they reinstalled. I'll check that link

**Comment by alexbelgium** [comment]
> Thanks. Just to clarify by app you mean the addon? You have made it work with hassio but don't have info about it's actual working? I could see some issue where somebody stated that they deleted the addon but it still requested the old totp code when they reinstalled. I'll check that link

Exactly! I only use around 5 of my 90+ add-ons. Usually I've spent hours setting them due to requests from people, and spend hours supporting them. Usually it's just a wrapping around an upstream docker image ; which is why things not strictly related to HA should be addressed through those upstream repositories where the people who actually set up the docker container can help.

It is strictly impossible for me to learn the non-standard way (such as you are requesting, to circumvent totp) of so many web apps proposed as add-ons. If security was properly implemented on guacamole, it should prevent accessing data without totp as this would allow an attacker with access to your local files.

**Comment by dasb00ter** [comment]
Thanks 👍 for taking the time to clarify.

**Comment by alexbelgium** [comment]
With pleasure hope it will work! Otherwise if you just delete the whole config folder you'll reset the add-on and restart anew
