### ISSUE TITLE
Qbittorrent not starting

### ISSUE THREAD

**Issue by Nanianmichaels** [alexbelgium/hassio-addons#175]
**Which addon?**

* Addon name : Qbittorrent and Jackett
* Addon version : 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-5 and 0.20.371, respectively

**Describe the bug**

Updating to the mentioned addon versions makes them not able to start, with the error messages being "Image ghcr.io/alexbelgium/qbittorrent-amd64:14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-5 does not exist for addon_db21ed7f_qbittorrent" and "Image ghcr.io/alexbelgium/jackett-amd64:0.20.371 does not exist for addon_db21ed7f_jackett_nas"

**To Reproduce**

* Supervisor version: 2021.12.2
* Host system version: Debian 11 (Supervised install)

**Comment by alexbelgium** [comment]
Please refresh your repro manually and it should hopefully work - I had built the images this morning and it works on mine

**Comment by alexbelgium** [comment]
Sorry I've implemented autobuild and it caused some issues with the set up. For those addons it will be solved. For other addons I had to revert

**Comment by alexbelgium** [comment]
For qBittorrent : 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-5 will work.
For Jackett : 0.20.371 should work in around 5 min

**Comment by Nanianmichaels** [comment]
> For qBittorrent : 14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-5 will work. For Jackett : 0.20.371 should work in around 5 min

Sorry for the delay, I was away during the whole day.

Can confirm that Jacket started working again after a new update.

qBittorrent still complains that "Image ghcr.io/alexbelgium/qbittorrent-amd64:14.3.9.99202110311443-7435-01519b5e7ubuntu20.04.1-ls166-5 does not exist for addon_db21ed7f_qbittorrent", even after a HA restart.

Can try updating the repository manually, though I'd need pointers on how to do it.

**Comment by alexbelgium** [comment]
OK thanks... Weird... Hopefully I'll have solved those build issues in the next couple days. I'll push  new version - 6 to see if it helps

**Comment by alexbelgium** [comment]
Good news! Well that's already a start. Thanks for the feedback I'm relieved because I thought it had know understand and had working images for those addons at least :) thanks

**Comment by alexbelgium** [comment]
I deeply apologize. I enabled autobuild as recommended by the HA guidelines, and it brought 2 big issues :
- Multi-arch base images are not supported (it needs a pull --platform tag that is not implemented yet, and the system is very complex to fork and customize)
- Upgrade from a locally built addon to an autobuilt addon is not supported : the addon still tries to locally build and then provides a failure message as it doesn't find a local image...

I have decided to revert the changes. This means that everyone that has installed the new versions pushed since 2 days will have to restore a backup, or uninstall the app and reinstall it...

Here is the full procedure : 
1. Manually refresh the repository by going in the repository section (the same place your added my custom repo to your system) and click on reload. This will refresh the repositories and allow you to install the new corrected addon versions (or wait 1 day)
2. if you have a backup : 
       - restore the backup
       - hopefully everything should work directly, as for most of my addons the data is stored out of the addon
       - DO NOT update BEFORE you had refreshed the repo, or you will face the issue again
3. if you didn't have a backup : 
      - uninstalling the app is the only solution
      - if you're lucky, everything could work directly, as for most of my addons the data is stored out of the addon
      - DO NOT update BEFORE you had refreshed the repo, or you will face the issue again

Thanks for your understanding.
