### ISSUE TITLE
[Portainer] Unnecessary binary content in backup file

### ISSUE THREAD

**Issue by lmagyar** [alexbelgium/hassio-addons#247]
Portainer

- Addon name : Portainer
- Addon version : 2.11.1-TESTDONOTUPDATE (as a fresh new install I wasn't able to install the non-latest version)

**Describe the bug**

Backup contains lot of binary content and has 100MB size, original/deprecated add-on's backup is only 1MB, there is:
- image.tar (286MB)
- data/docker_config/cli-plugins/docker-compose (20MB)

In my [fork](https://github.com/lmagyar/homeassistant-addon-portainer) of the deprecated add-on I've added these exclusions to the config (I had no problem with the image.tar):
```yaml
backup_exclude:
  - backups
  - docker_config/cli-plugins
```
Disclaimer: My add-on development knowledge is very basic.

**To Reproduce**

1. Fresh new add-on install
2. Create backup

**Full addon log**

**Full addon config**

**System**

- Supervisor version: supervisor-2022.03.3
- Host system version: Home Assistant OS 7.4

**Comment by alexbelgium** [comment]
Hi,

The backup size is mainly because HA stores a copy of the image as it is locally build. I wanted to enable autobuilds but can’t due to this bug in supervisor : [home-assistant/supervisor#3414 6](https://github.com/home-assistant/supervisor/issues/3414). This bug causes all addons updates to fail if I enable auto builds.

I've sent a request for people to go like my supervisor issue to highlight the issue to devs and help ensure that they see it and solve it as soon as possible to enable autobuilds : less sd wear, faster updates, decrease backup size, ensuring it works on supervised installations without weird tweaks, allowing me to check if builds succeed directly when updating instead of you testing it when local building…

Already I'll include the elements you've proposed to removed to backup, that will already help :-)

Thanks

**Comment by lmagyar** [comment]
Oh, I see the reason for image.tar. :(
I've "up-voted" your Supervisor issue.
Closing this issue, because you are already working on the root cause of the problem.
