### ISSUE TITLE
[Radarr/Sonarr] No access to media folder

### ISSUE THREAD

**Issue by przerada** [alexbelgium/hassio-addons#299]
**Radarr NAS/ Sonarr NAS**

- Addon name : Radarr NAS / Sonarr NAS
- Addon version : Latest

**Describe the bug**

Hi I have No access to media folder, I see here that the config.json have media:rw set but when I trying to add folder I see empty media folder and even that I can’t set this folder for a download.
I have mounted ssd drive via this script https://gist.github.com/eklex/c5fac345de5be9d9bc420510617c86b5, Plex Media Server add-on from community repo have access to this media folder and folders on this drive too, when I check this https://github.com/hassio-addons/addon-plex/blob/main/plex/config.yaml we can see that media have :rw to and I have access.
I see only one difference in map section, media folder in your config is on the 3rd place, config and share folders works at my installation fine.
Do anyone here have same problem? Maybe you can change the place of folders in config or tell me how to check anything in my installation?
I have latest Hassio system on raspberry pi

**Comment by alexbelgium** [comment]
Hi,

Indeed there is a single place to mount media folders so I don't see why it wouldn't work... Otherwise, why don't you mount your disk directly in Radarr & Sonarr using the localdisks option ? Then it will be mounted in /mnt. Perhaps not what you want but it could work ;-)

Btw do you have the same user ID & group ID specified in the addons and in the script used to mount ? The best is to keep 0 & 0 to be sure to be root, that should avoid some permissions issues

**Comment by alexbelgium** [comment]
I've put a media file and a folder in my HA media folder, reinstalled radarr nas, and I can see both in /media... So the media folder is correctly mounted. If you can't see it, perhaps it is a permission issue... And is there no error messages in the supervisor log when running the addon? Errors from the addon log would probably not be relevant if it is a HA permission or apparmor issue...

**Comment by przerada** [comment]
Oh my gosh, you helped me, the problem was ID and Group ID, one the 0 everything is fine, thanks for your help and sorry for bothering you.

**Comment by alexbelgium** [comment]
That's great, happy it works!
