### ISSUE TITLE
Request: damselfly photo gallery

### ISSUE THREAD

**Issue by mohyat** [alexbelgium/hassio-addons#32]
Can you make damselfly photo gallery addon for HA.

[](https://damselfly.info/)

**Comment by alexbelgium** [comment]
Hi, I've already 2 specific addons for photo gallery, plus nextcloud that can be used as such. Is there a specific added value of this one? BTW I couldn't find it on Google. Best regards

**Comment by mohyat** [comment]
Is there a specific added value of this one?
Yes.

Read this: [link](https://github.com/Webreaper/Damselfly)

**Comment by alexbelgium** [comment]
You are asking me to freely, out of my own time, create an addon for a tool for which you are the only requester. Afterwards, I'll do updates, maintenances, and support. All that out of my free time, and in addition to my family and full time job.

The least you could do is take the time to summarize me the need, instead of providing a github page for me to go through.
