### ISSUE TITLE
✨ ABOUT REQUESTS

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#326]
Hi everyone,

When I was beginning to use HomeAssistant, I saw tons of possibilities with the system and was a bit frustrated when an app that I wanted was not available as an addon. I therefore started this repo. When people started asking me to port new apps that I was not using myself, I understood where they came from and tried to implement as many as possible.

Everyone is therefore free to make a request through the Issues system. However, I do not provide a guarantee neither of timings, nor of implementation. Globally, the key factors for implementation by order of priority are : 
- Is the image from linuxserver.io ? They have the best dockerhub images, that are very easily converted in addons
- Number of people interested in the addon
- Quality of existing dockerhub image

Maintaining all those addons take a lot of time, although I recognize that people help me a lot through bug reports & proposing PR to improve the repo. So please don't hesitate to help improve things where you can, it will be much appreciated and will benefit everyone!

Have a nice day everyone

**Comment by KairuByte** [comment]
As someone with a longish standing request that is slowly being worked on, I appreciate all you do. Even if the end result is something that doesn't happen, the effort alone is appreciated. I personally do not *expect* anything, as you are doing this in your free time. You owe us nothing, after all. \^_\^

**Comment by alexbelgium** [comment]
Good idea. I see that the HA community addon did this. I'll look at it as an improvement! I just want to keep visibility on the requests so I don't forget them :) I've also added a script that checks if issues or requests are open, and notify those on top of the relevant addon readme, I'll have to see if the github api exposes discussions in the same way as issues. Thanks for the proposal!

**Comment by alexbelgium** [comment]
I don't think I'm be able to add new addons for the moment

**Comment by richardwonka** [comment]
A note - and a question - on the documentation.

I love that the available options are all listed here, even with examples. 

There is one piece of information missing: _Where_ do I put these options? Which file do I need to edit to add them?

e.g.: I get the error message in the admin dashboard about missing the default phone region. 

The documentation tells me that I can set `default_phone_region: de` 

_But where?_

**Comment by alexbelgium** [comment]
Hi, thanks for the feedback - options can be configured from the addon options page within homeassistant. Watch-out that if they are not used, they might be hidden.

<img width="515" alt="image" src="https://github.com/user-attachments/assets/85bb7625-7abf-4360-9869-920ab287b9a2">
<img width="514" alt="image" src="https://github.com/user-attachments/assets/d60933e1-5485-4d17-868a-9c9bcebbd1a3">

**Comment by richardwonka** [comment]
That’s the odd thing. The example was not in the UI. When I added the option in yaml, the ui refused to save the config.

**Comment by alexbelgium** [comment]
Well I guess you are talking about Nextcloud, which is the only add-on using this option. On my system I can see the option, and it is in the config, so I'm sure it exists. Now the only reason that you wouldn't see it in the nextcloud add-on options were if that option is hidden and needs to be shown by the switch in bottom right of my first screen shot

**Comment by richardwonka** [comment]
Yes, it is about nextcloud, sorry I hadn’t specified. 

I had used that switch for the hidden options, that was the first place I looked. 

I’m running the latest available nextcloud add-on on current Homeassistant and it was not showing and refusing to let me add the option. 

I am at a loss as to where to look now.

**Comment by ExquisiteMetropolis** [comment]
Hi Alex,

Recently I tested to see if this add-on (not yours) would suit my needs: https://community.home-assistant.io/t/home-assistant-add-on-ads-b-multi-portal-feeder-flightradar24-and-flightaware/345563 
It almost did. ;)

After a power failure, I miss BIAS-T in the setup, so my LNA filter no longer works, because power is not provided.
This needs to be software activated via a parameter in the container/add-in. No supported (yet).
Too bad. So I switched back to these seperate docker containers below, which conflicts with my goal to switch to HA OS on my Pi instead of a supervised setup.

Basically this setup feeds data I pickup from aircraft in the area and feeds it to several tracking websites. Very cool stuff if you're an aviation-geek. There are many people around the world who do this, and form the basis (community) for websites like Flightradar24.

I've seen that the plugin I linked above, also uses other github repo's to realize the add-in.
Your repositority in HA is very impressive, and I am a happy user of a few of them. So thanks!

How complicated would it be, to transform these containers into add-on(s) for HA? Potentially you could expand your repo with ADSB feeding. :)
I have a technical background myself, so I would welcome the learning curve on how to do this (if you point me in the right direction?), or I can help you test the work to be done.

ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest

ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
ghcr.io/sdr-enthusiasts/docker-piaware:latest
ghcr.io/sdr-enthusiasts/docker-planefinder:latest
ghcr.io/sdr-enthusiasts/docker-adsbexchange:latest
ghcr.io/sdr-enthusiasts/docker-radarbox:latest

And #dare-to-ask ;-)
The same need goes for thise one: https://github.com/fboaventura/dckr-mrtg
I know HA supports SNMP, however a clear setup manual for that is yet to be conceived and I would lose all my history.

**Comment by alexbelgium** [comment]
Hi, sorry I don't have time anymore alas to add new addons. But I had written a short guide how to build addons. When I started I had no docker or HA knowledge and build all by trial ;-) https://github.com/alexbelgium/hassio-addons/wiki/Building-an-addon

Another way would be to use portainer to launch the docker by yourself - there is lots of documentation out there on using portainer to start a container

I would also recommend to check around if there is no other repo fitting your needs as indeed I think I already read in the past about flightradar addons !

Good luck, and have fun with HA!
