### ISSUE TITLE
[NextCloud] Addon Slow

### ISSUE THREAD

**Issue by Neotastisch** [alexbelgium/hassio-addons#350]
(Me again, sorry about that)

Well, ive tryed the "original" Addon and this one, i really have to say that the "original" one is way faster...

On the "original" Addon it uses about 7% of the Cpu, but this modification uses 0%, could you please try making it more so it can be faster 

![image](https://user-images.githubusercontent.com/54811660/172239594-7c23ce8c-36c9-46f9-a35f-1d90fd74ea7d.png)

If thats not possible, you can just close this issue...

Thanks :D

**Comment by alexbelgium** [comment]
Hi, I see your point but it is hard to compare as 8t is not the same version of the app. Haberda is on v23 and here it is v24 so it is difficult to see if the potential slowness on your system is from the version or the modifications... I don't see what could limit cpu usage expect the app itself! On my aarch64 it works great and fast...

**Comment by Neotastisch** [comment]
> Hi, I see your point but it is hard to compare as 8t is not the same version of the app. Haberda is on v23 and here it is v24 so it is difficult to see if the potential slowness on your system is from the version or the modifications... I don't see what could limit cpu usage expect the app itself! On my aarch64 it works great and fast... 

Mhmm is there anyway to demonstrate to you? Maybe I could create an temporary account

Username: test
Password: ilikenextcloud
Ip: nc.neohome.tk

**Comment by alexbelgium** [comment]
Thanks, I've connected but actually have a limited user access so can't see the system. 

I could still do some tests (your nextcloud vs mine) :
- Speed of site load : 16.27s vs 14.92s => similar
- Speed of photos page load : 27.17s vs 20.07s
- Speed of opening the nextcloud manual : 17.96s vs 5.47s => my connection seems to load faster. Are you sure it's not your tunnel that is limiting the speed?
- Visual aspect : yours is very nice!

The only speed difference between us seems to be the duration of opening files, which could be due to the tunnel.

I'll install haberda's one to test speed

**Comment by Neotastisch** [comment]
Yeah, i cant give you admin access since there is private stuff on it
Im pretty sure its not the tunnel since my Homeassistant page loads fast
And thanks :D

**Comment by alexbelgium** [comment]
I've done some tests but the speed difference isn't huge on my system. However, their lack of user ssl certificates prevents to perform the exact same analysis. 

The only thing I see that could impact speed would be some apps that I install by default for nextcloud...

**Comment by Neotastisch** [comment]
Strange, i guess i have to live with it...
My Apps:
![image](https://user-images.githubusercontent.com/54811660/172330945-e165bca0-d724-4ba0-a024-047edb2ca0f9.png)


Bdw: Do you know how i can use my external hard drive for saving and not the default one?

**Comment by alexbelgium** [comment]
Motioneye is a HUGE drain on resources in my experience... I had to delete it from my system as it made everything so slow and hot... 

On my system, I have : adguard home ; Emby ; Filebrowser ; Home Assistant Google backup ; Joal ; Let's encrypt ; MariaDB ; Nginx home assistant ssl proxy ; Portainer ; Qbittorrent ; Repository updater ; Samba NAS ; SSH & web terminal ; Vaultwarden & webtrees

It works very fine with minimal load! But honestly moving from a rpi3 to rpi4b was a big impact on speed

**Comment by Neotastisch** [comment]
The problem is that i have a camera with motion detection on my system, im currently using an rpi3b

**Comment by Neotastisch** [comment]
but i guess i can live without the camera

**Comment by alexbelgium** [comment]
I loved the idea of motion detection but I removed it from my system due to the impact on resources... However I saw that both my camera (Dahua & tapo c310) have integrations that get the motion alarms from the camera themselves! Therefore I don't have to generate the motion verification on my own system

And I had tons of false alarms with motioneye, whenever it was raining (which happens a lot where I live) it made alarms!

**Comment by alexbelgium** [comment]
Thanks, and have fun with your system!

**Comment by alexbelgium** [comment]
BTW you can use an automation to activate motioneye at specific times,like when you are away
