### ISSUE TITLE
Mealie V1.00 support for Arm64 (such as Rpi)

### ISSUE THREAD

**Issue by joggesan** [alexbelgium/hassio-addons#469]
Hi Alex
Thanks for some great addons.
I've noticed that you only support version 0.4.3 for AR; devices such as the Raspberry Pi. Raspberry Pi can also run 64bit ARM (eg.:https://github.com/home-assistant/operating-system/releases/download/8.5/haos_rpi4-64-8.5.img.xz), which perfectly well supports version 1.00beta4 (currently the newest version).
I was hoping you could change your build.json to support v1.00 on 64bit ARM devices?

Thanks!

**Comment by alexbelgium** [comment]
Hello, actually this request is already open here : https://github.com/alexbelgium/hassio-addons/issues/356
Due to the way mealie 1.0 is created, I prefer to have a all-in-one solution instead of 2 separated addons. We are lucky that a dev is already working on this, and have put in place images for amd64! He is also working on images for aarch64 https://github.com/hendrix04/mealie-combined/issues/2#issuecomment-1163043687, as soon as those are available, I'll update my ARM 64 bit addon to v1.0

**Comment by alexbelgium** [comment]
I'll therefore close this request, as it is already tracked elsewhere. Thanks for raising the point!
