### ISSUE TITLE
[Mealie] "env: can't execute 'bashio': No such file or directory"

### ISSUE THREAD

**Issue by LoganJFisher** [alexbelgium/hassio-addons#505]
I've installed the Mealie addon, but when I go to start it, the log returns "env: can't execute 'bashio': No such file or directory" and it fails to start.

I have no idea what to do to resolve this. Any suggestions?

**Comment by alexbelgium** [comment]
"Arm/v7 Support
Mealie will no longer build in CI/CD due to a issue with the rust compiler on 32 bit devices. You can reference this issue on the matrix-org/synapse Github page that are facing a similar issue. You may still be able to build the docker image you-self."

https://hay-kot.github.io/mealie/changelog/v0.5.0/

Sorry I'll remove the image to prevent confusion, and I don't have anymore a device to fix armv7 issues...

**Comment by alexbelgium** [comment]
Probably, Mealie doesn't support 32 bit anymore in their published images I use
