### ISSUE TITLE
Qbittorrent backup with HASS is huge

### ISSUE THREAD

**Issue by goooroooX** [alexbelgium/hassio-addons#55]
Hi!

I've found out that backup taken by HASS was increased in size dramatically because of Qbittorrent addon.
When backed up, this addon includes not just a configuration, but also container image, which is ~600Mb in size.
Is it possible to do something with this, exclude images? By backup increased 3 times in size...

![image](https://user-images.githubusercontent.com/27283908/135366856-7037f04c-0e75-4f14-9d6a-3cdc10b1de0e.png)

![image](https://user-images.githubusercontent.com/27283908/135367253-0a6a38f0-efb0-4d5a-be0f-595c8f2a5a2e.png)

**Comment by alexbelgium** [comment]
Hello, you could simply backup only /config, where qbittorrent config is stored, and deselect qbittorrent from your backup scheme. I think the whole image backup is because it is built locally...

**Comment by goooroooX** [comment]
Well, can't say it's so simple. I can't find baskup scheme in HASS :)
This is the only add-on with such behavior.

**Comment by alexbelgium** [comment]
Ah ah, sorry. I use a specific addon for automatic backups with uploads to Google drive that is great. I've actually created a fake Google account for the sole purpose of storing my backups, to avoid taking too much space on my rpi. https://community.home-assistant.io/t/add-on-home-assistant-google-drive-backup/107928 

It is the best backup addon I've seen on HA. One of its many advantages is to allow partial backups, by deselecting specific addons that we don't want to backup. 

All my addons will alas have this behaviour, as they are built locally on your HA instance instead of being stored on being built as images by the dev and uploaded on dockerhub. I don't have much time to allocate to my addons, so I can't put in place an auto build architecture like Frenck does, for example, who manages the official and community addins...

As I know that, I've put in place this system that my addon options are usually stored in the HA folder /config. This allows saving their most important part without having to backup the whole addon... My own backup files are 5go big. They are generated every 7 days locally during the night, then uploaded to Google drive and locally removed by the addon I mentioned above. This allows me to backup everything, while not taking any room on my rpi...

Hope this will help you! I don't think an option exists to remove selectively the image from the backup. It would have to be implemented by the Supervisor dev team of HA...

**Comment by goooroooX** [comment]
Ok, got it. Thank you for update.
Actually, this is definitely something need to be enhanced by HA team, like generic settings for backing up addons.
Google Drive Backup is great, no doubts, and I have found the option you are talking about - partial backups. My only concern is that I can install a new addon and forget to include it to backup. 

Thank you for your great repository!

**Comment by alexbelgium** [comment]
Actually, newly installed addons are automatically added to the backup - this addon is truly one of the best developed ones that I have installed on my HA...

BTW you gave me an idea and I'll see if it is possible to trick the addon in not backup ing it's image using an exclusion feature that I haven't tried yet... If it works ill let you know :)

**Comment by alexbelgium** [comment]
I've made a test - perhaps now the image is excluded from the image :-)
Would it be possible for you to test?

**Comment by goooroooX** [comment]
Sure, just tell me how I can do it.

**Comment by alexbelgium** [comment]
Well if you just update to the new version "14.3.8.99202109100310-7422-338d9a084ubuntu20.04.1-ls154-3-test", I've modified the addon to exclude from backup the */image.tar. it could work :-)

**Comment by goooroooX** [comment]
Will do, once few really slow torrent will finalize :)

**Comment by alexbelgium** [comment]
Mmh it doesn't seem to work...

**Comment by goooroooX** [comment]
Yep. 
Confirmed - test version still includes images.

**Comment by alexbelgium** [comment]
Then it's a supervisor limitation... Sorry the only solution I can propose is to only backup /config

**Comment by goooroooX** [comment]
No problem, I've reconfigured Google Backup add-on to skip qBittorrent.
Thank you for assistance.

**Comment by alexbelgium** [comment]
My pleasure, have a great day!
