### ISSUE TITLE
✨ [REQUEST] AutoBrr (companion to Radarr an Sonarr)

### ISSUE THREAD

**Issue by hacshacdgacs** [alexbelgium/hassio-addons#581]
**Which addon?**
AutoBrr
"autobrr is a general purpose download automation tool for torrents, not just for racing. Connect it with tools like Radarr and Sonarr along with Plex and you have a fantastic automated media setup - from download to enjoying your favorite content."

"How this is different from sonarr, radarr, lidarr?"
Instead of searching the site via the api in set intervals it monitors the irc announce channel for every new upload and downloads anything matching what you want the moment its posted. This is an important distinction if youre racing, youll get the file instantly instead of in 30 minutes when the next search is performed.
It also supports all content types, not just movies/tv/books.

Gitbhub Link
https://github.com/autobrr/autobrr

**Comment by cronner** [comment]
This would be really nice :)

**Comment by diamant-x** [comment]
I'm not sure this is something that a much majority of torrent users might need.
It is mentioned "not just for racing" but then in second paragraph you say "youll get the file instantly instead of in 30 minutes".
I would say target users of this need might not run a commodity HA as their host, and instead might have some other host (such a seedbox) where a HA-addon might not be applicable.

The only point I do see might be relevant for is "supports all content types, not just movies/tv/books". I'm not such user so can't understand how much of a gap is that, and how much of a pain it is to search once very time for the content one might need need.

**Comment by cronner** [comment]
It's lighter on the system than Sonarr & Radarr so some people are gonna use it on their HA install instead of Sonarr & Radarr install just because of that.

**Comment by alexbelgium** [comment]
Hi, addon pushed

**Comment by hacshacdgacs** [comment]
Sorry for the late reply, I've had this installed for the last week and it's been working great. Thanks

**Comment by alexbelgium** [comment]
Thanks for the feedback!
