### ISSUE TITLE
Mealie - High Ram Usage

### ISSUE THREAD

**Issue by bobloadmire** [alexbelgium/hassio-addons#829]
Works great, but a new install with nothing in it is chewing 600m of my rpi4 2gb ram. This seems unreasonably high, is there anything that can be done?

**Comment by alexbelgium** [comment]
Hi, sorry this is likely due to upstream image. Plus, please use templates for issues. Thanks.

A quick search on the upstream repo shows this was already encountered : https://github.com/hay-kot/mealie/issues/654

I've set those values in the newly pushed version. If this doesn't help, I don't see what I can do from the addon side

**Comment by bobloadmire** [comment]
Hey thanks just wanted to make sure something easy wasn't getting overlooked. Sorry about the template, the flow dialogue didn't come up for some reason from where I hit new issue. Thanks!

**Comment by alexbelgium** [comment]
No problem, it showed me that I had a bug in the config.yaml to disable blank issues so actually it helped :)

Regarding size or ram optimization alas I can't do much as often it is linked in the upstream container image. In this case I've reduced the number of threads in a new version so it should limit ram usage, however be aware that lots of graphic addons have relatively high ram usage

**Comment by bobloadmire** [comment]
just for reference, whatever you changed helped a little, went fom 600m to 480m. still using 100m more than HA itself lol

**Comment by alexbelgium** [comment]
Thanks. I'll close it as I don't see what can be changed more but if you see any other way to decrease ram usage please post here or make a PR. Thanks!
